<?php
/**
 * G2-M08 Morning Digest — Non Sequitur
 *
 * Sprint 1, Gate 2 Micro-snippet 08
 * S1.10 — Morning Digest (daily 0600 CST, top 20 items)
 * GitLab Issue #17
 *
 * @package NonSequitur
 * @since 1.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_action( 'ns_morning_digest_event', 'ns_send_morning_digest' );

/**
 * Send morning digest email with top 20 scored items from last 24h
 */
function ns_send_morning_digest() {
    $items = get_posts( array(
        'post_type'      => 'ns_feed_item',
        'posts_per_page' => 20,
        'meta_key'       => 'relevance_score',
        'orderby'        => 'meta_value_num',
        'order'          => 'DESC',
        'date_query'     => array(
            array( 'after' => '24 hours ago' ),
        ),
        'meta_query'     => array(
            array(
                'key'     => 'relevance_score',
                'value'   => '0',
                'compare' => '>',
                'type'    => 'NUMERIC',
            ),
        ),
    ) );

    if ( empty( $items ) ) {
        ns_log( 'digest', 'No scored items in last 24h. Skipping digest.' );
        return;
    }

    $subject = sprintf( '[Non Sequitur] Morning Digest — %s (%d items)',
        gmdate( 'M j, Y' ), count( $items ) );

    $body = '<html><body style="font-family:system-ui,-apple-system,sans-serif;max-width:700px;margin:0 auto;padding:20px;background:#0d1117;color:#c9d1d9;">';
    $body .= '<h1 style="color:#58a6ff;border-bottom:1px solid #21262d;padding-bottom:10px;">Non Sequitur — Morning Digest</h1>';
    $body .= '<p style="color:#8b949e;">' . gmdate( 'l, F j, Y' ) . ' | ' . count( $items ) . ' top items</p>';

    $grouped = array();
    foreach ( $items as $item ) {
        $domain = get_post_meta( $item->ID, 'domain_tag', true ) ?: 'uncategorized';
        $grouped[ $domain ][] = $item;
    }

    $domain_labels = array(
        'ai'         => 'AI & Machine Learning',
        'cyber'      => 'Cybersecurity',
        'innovation' => 'Innovation & Strategy',
        'fnw'        => 'Future of Nat\'l Security',
        'space'      => 'Space & Aerospace',
        'digital'    => 'Digital Transformation',
    );

    foreach ( $grouped as $domain => $domain_items ) {
        $label = isset( $domain_labels[ $domain ] ) ? $domain_labels[ $domain ] : ucfirst( $domain );
        $body .= '<h2 style="color:#f0883e;margin-top:25px;font-size:16px;">' . esc_html( $label ) . '</h2>';

        foreach ( $domain_items as $item ) {
            $score      = (int) get_post_meta( $item->ID, 'relevance_score', true );
            $source     = esc_html( get_post_meta( $item->ID, 'source_name', true ) );
            $source_url = esc_url( get_post_meta( $item->ID, 'source_url', true ) );
            $summary    = esc_html( get_post_meta( $item->ID, 'claude_summary', true ) );
            $score_color = $score >= 7 ? '#3fb950' : ( $score >= 4 ? '#d29922' : '#8b949e' );

            $body .= '<div style="margin:10px 0;padding:12px;background:#161b22;border-radius:6px;border-left:3px solid ' . $score_color . ';">';
            $body .= '<div style="display:flex;justify-content:space-between;align-items:center;">';
            $body .= '<a href="' . $source_url . '" style="color:#58a6ff;text-decoration:none;font-weight:600;font-size:14px;">' . esc_html( $item->post_title ) . '</a>';
            $body .= '<span style="color:' . $score_color . ';font-weight:700;font-size:14px;min-width:40px;text-align:right;">' . $score . '/10</span>';
            $body .= '</div>';
            $body .= '<div style="color:#8b949e;font-size:12px;margin-top:4px;">' . $source . '</div>';
            if ( $summary ) {
                $body .= '<div style="color:#c9d1d9;font-size:13px;margin-top:6px;">' . $summary . '</div>';
            }
            $body .= '</div>';
        }
    }

    $body .= '<hr style="border:none;border-top:1px solid #21262d;margin:30px 0;">';
    $body .= '<p style="color:#8b949e;font-size:12px;text-align:center;">Generated by Non Sequitur AI Pipeline | <a href="' . esc_url( admin_url( 'edit.php?post_type=ns_feed_item' ) ) . '" style="color:#58a6ff;">Open Dashboard</a></p>';
    $body .= '</body></html>';

    $admin_email = get_option( 'admin_email' );
    $headers = array(
        'Content-Type: text/html; charset=UTF-8',
        'From: Non Sequitur <noreply@' . wp_parse_url( home_url(), PHP_URL_HOST ) . '>',
    );

    $sent = wp_mail( $admin_email, $subject, $body, $headers );
    ns_log( 'digest', $sent ? 'Morning digest sent to ' . $admin_email : 'Failed to send digest.' );
}
