image: busybox

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp the-markdown/the-markdown-prototype.html public/index.html
    - cp the-markdown/TheMarkdown_Architecture_Diagram.html public/architecture.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
